repository: worldmusic/worldmusic.github.io
title: World Music Textbook
author: Maintained by Christopher Witulski
email: editors@worldmusictextbook.org
description: >- # ignores newlines
  An online and open resource for
  teaching and learning ethnomusicology and musicology
timezone: America/New_York
baseurl: ""
url: https://worldmusictextbook.org
facebook_username: WorldMusicTextbook
twitter_username: music_textbook
collections:
  - resources

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
sass:
  sass_dir: /_sass