repository: worldmusic/worldmusic.github.io
title: World Music Textbook
author: Maintained by Christopher Witulski
email: editors@worldmusictextbook.org
description: >- # this means to ignore newlines until "baseurl:"
  An online and open resource for
  teaching and learning ethnomusicology and musicology
timezone: America/New_York
baseurl: "" # the subpath of your site, e.g. /blog
url: https://worldmusictextbook.org # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: WorldMusicTextbook
twitter_username: music_textbook
collections:
  - resources

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
sass:
  sass_dir: /_sass